name: Multi container
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build test client
#        uses: docker/build-push-action@v2
#        with:
#          context: ./client
#          file: ./client/Dockerfile.dev
#          load: true
#          tags: iuriinedostup/react-test
#
#      - name: test app
#        run: docker run -e CI=true iuriinedostup/react-test npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build client
#        uses: docker/build-push-action@v2
#        with:
#          context: ./client
#          file: ./client/Dockerfile.dev
#          push: true
#          tags: iuriinedostup/multi-client
#
#      - name: Build nginx
#        uses: docker/build-push-action@v2
#        with:
#          context: ./nginx
#          file: ./nginx/Dockerfile.dev
#          push: true
#          tags: iuriinedostup/multi-nginx
#      - name: Build server
#        uses: docker/build-push-action@v2
#        with:
#          context: ./server
#          file: ./server/Dockerfile.dev
#          push: true
#          tags: iuriinedostup/multi-server
#
#      - name: Build worker
#        uses: docker/build-push-action@v2
#        with:
#          context: ./worker
#          file: ./worker/Dockerfile.dev
#          push: true
#          tags: iuriinedostup/multi-worker

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: multi-docker-app
#          environment_name: multi-docker-env
#          existing_bucket_name: elasticbeanstalk-eu-west-1-054496151910
#          region: eu-west-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
